name: Generate Baseline Profiles

on:
  workflow_dispatch

jobs:
  generateBaselineProfiles:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Google Services file for release
        run: touch app/src/release/google-services.json

      - name: Create Google Services file for benchmarkRelease
        run: |
          mkdir app/src/benchmarkRelease
          touch app/src/benchmarkRelease/google-services.json

      - name: Create Google Services file for nonMinifiedRelease
        run: |
          mkdir app/src/nonMinifiedRelease
          touch app/src/nonMinifiedRelease/google-services.json

      - name: Put Google Services Data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $DATA > app/src/release/google-services.json
          echo $DATA > app/src/benchmarkRelease/google-services.json
          echo $DATA > app/src/nonMinifiedRelease/google-services.json

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      # This allows us to build most of what we need without the emulator running and using resources
      - name: Build app and benchmark
        run: ./gradlew :performance:benchmark:assembleBenchmark

      # Cleans managed device if previously settle and space currently is not available
      - name: Clean Gradle Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      # Generates Baseline Profile
      - name: Generate Baseline profile gradle task
        run: ./gradlew generateBaselineProfile -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20 -Dorg.gradle.workers.max=4

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Generate baseline profiles"
          title: "Generate baseline profiles"
          delete-branch: true
          reviewers: sahianmol1
          branch: actions/baseline-profiles