name: Static Kotlin Code Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  detekt:
    if: github.event.pull_request.draft == false
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Run Detekt using the ruleset in detekt.yml
        run: ./gradlew detektAll