name: Run tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  unitTests:
    if: github.event.pull_request.draft == false
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Google Services file
        run: touch app/src/release/google-services.json

      - name: Put Google Services Data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/src/release/google-services.json

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Run unit tests gradle task
        run: ./gradlew test